In [1]:
import pandas as pd

df = pd.read_csv(r"C:\online_retail\data\raw\online_retail_II.csv")

In [2]:
df.shape

(1067371, 8)

In [3]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  str
 1   StockCode    1067371 non-null  str
 2   Description  1062989 non-null  str
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  str
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 65.1 MB

In [5]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(34335)

In [7]:
df.describe()

           Quantity         Price    Customer ID
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

In [8]:
df.nunique()

Invoice        53628
StockCode       5305
Description     5698
Quantity        1057
InvoiceDate    47635
Price           2807
Customer ID     5942
Country           43
dtype: int64

In [9]:
df["Quantity"].value_counts().head(20)

Quantity
 1     294346
 2     159960
 12    121745
 6      85299
 3      72638
 4      72382
 24     47036
 10     40956
 8      25819
 5      23165
 48     12162
 25      9673
 20      8983
-1       8897
 16      7907
 36      7569
 7       4857
 9       4094
 72      3845
 18      3636
Name: count, dtype: int64

In [10]:
(df["Quantity"] < 0).sum()

np.int64(22950)

In [11]:
df[df["Quantity"] < 0].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
183,C489449,21871,SAVE THE PLANET MUG,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
184,C489449,84946,ANTIQUE SILVER TEA GLASS ETCHED,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
185,C489449,84970S,HANGING HEART ZINC T-LIGHT HOLDER,-24,2009-12-01 10:33:00,0.85,16321.0,Australia
186,C489449,22090,PAPER BUNTING RETRO SPOTS,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
196,C489459,90200A,PURPLE SWEETHEART BRACELET,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom

In [12]:
df[df["Quantity"] < 0].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
183,C489449,21871,SAVE THE PLANET MUG,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
184,C489449,84946,ANTIQUE SILVER TEA GLASS ETCHED,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
185,C489449,84970S,HANGING HEART ZINC T-LIGHT HOLDER,-24,2009-12-01 10:33:00,0.85,16321.0,Australia
186,C489449,22090,PAPER BUNTING RETRO SPOTS,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
196,C489459,90200A,PURPLE SWEETHEART BRACELET,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom

In [13]:
(df["Price"] <= 0).sum()

np.int64(6207)

In [14]:
df[df["Price"] <= 0].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3162,489660,35956,lost,-1043,2009-12-01 17:43:00,0.0,NaN,United Kingdom
3168,489663,35605A,damages,-117,2009-12-01 18:02:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom

In [15]:
(df["Price"] <= 0).sum()

np.int64(6207)

In [16]:
df[df["Price"] <= 0].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3162,489660,35956,lost,-1043,2009-12-01 17:43:00,0.0,NaN,United Kingdom
3168,489663,35605A,damages,-117,2009-12-01 18:02:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom

In [17]:
df[df["Price"] < 0].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom
825444,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
825445,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

Because this dataset contains invoices where cancellations can be represented by an invoice beginning with C

In [18]:
df["Amount"] = df["Quantity"] * df["Price"]

df[["Invoice", "StockCode", "Description", "Quantity", "Price", "Amount"]].head(20)

,Invoice,StockCode,Description,Quantity,Price,Amount
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,6.95,83.40
1,489434,79323P,PINK CHERRY LIGHTS,12,6.75,81.00
2,489434,79323W,WHITE CHERRY LIGHTS,12,6.75,81.00
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2.10,100.80
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,1.25,30.00
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,1.65,39.60
6,489434,21871,SAVE THE PLANET MUG,24,1.25,30.00
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,5.95,59.50
8,489435,22350,CAT BOWL,12,2.55,30.60
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,3.75,45.00
10,489435,22195,HEART MEASURING SPOONS LARGE,24,1.65,39.60
11,489435,22353,LUNCHBOX WITH CUTLERY FAIRY CAKES,12,2.55,30.60
12,489436,48173C,DOOR MAT BLACK FLOCK,10,5.95,59.50
13,489436,21755,LOVE BUILDING BLOCK WORD,18,5.45,98.10
14,489436,21754,HOME BUILDING BLOCK WORD,3,5.95,17.85
15,489436,84879,ASSORTED COLOUR BIRD ORNAMENT,16,1.69,27.04
16,489436,22119,PEACE WOODEN BLOCK LETTERS,3,6.95,20.85
17,489436,22142,CHRISTMAS CRAFT WHITE FAIRY,12,1.45,17.40
18,489436,22296,HEART IVORY TRELLIS LARGE,12,1.65,19.80
19,489436,22295,HEART FILIGREE DOVE LARGE,12,1.65,19.80

In [19]:
df["Amount"].describe()

count    1.067371e+06
mean     1.806987e+01
std      2.924202e+02
min     -1.684696e+05
25%      3.750000e+00
50%      9.900000e+00
75%      1.770000e+01
max      1.684696e+05
Name: Amount, dtype: float64

In [20]:
df["Invoice"].str.startswith("C").sum()

np.int64(19494)

In [21]:
df[df["Invoice"].str.startswith("C")].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Amount
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia,-35.40
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia,-9.90
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia,-17.00
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia,-12.60
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia,-35.40
183,C489449,21871,SAVE THE PLANET MUG,-12,2009-12-01 10:33:00,1.25,16321.0,Australia,-15.00
184,C489449,84946,ANTIQUE SILVER TEA GLASS ETCHED,-12,2009-12-01 10:33:00,1.25,16321.0,Australia,-15.00
185,C489449,84970S,HANGING HEART ZINC T-LIGHT HOLDER,-24,2009-12-01 10:33:00,0.85,16321.0,Australia,-20.40
186,C489449,22090,PAPER BUNTING RETRO SPOTS,-12,2009-12-01 10:33:00,2.95,16321.0,Australia,-35.40
196,C489459,90200A,PURPLE SWEETHEART BRACELET,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom,-12.75

In [22]:
df["Invoice"].astype(str).str[0].value_counts()

Invoice
5    939382
4    108489
C     19494
A         6
Name: count, dtype: int64

In [23]:
df["InvoiceType"] = df["Invoice"].astype(str).str[0]

df.groupby("InvoiceType")["Invoice"].agg(
    count="count",
    unique_invoices="nunique"
)

              count  unique_invoices
InvoiceType
4            108489             5261
5            939382            40069
A                 6                6
C             19494             8292

In [24]:
invoice_country = (
    df.assign(InvoiceType=df["Invoice"].astype(str).str[0])
      .query("InvoiceType in ['C', 'A']")
      .groupby(["InvoiceType", "Country"])["Invoice"]
      .nunique()
      .reset_index(name="Unique_Invoices")
      .sort_values(["InvoiceType", "Unique_Invoices"], ascending=[True, False])
)

invoice_country

   InvoiceType               Country  Unique_Invoices
0            A        United Kingdom                6
35           C        United Kingdom             7315
13           C               Germany              306
9            C                  EIRE              180
12           C                France              124
4            C               Belgium               34
30           C                 Spain               34
32           C           Switzerland               30
26           C              Portugal               29
17           C                 Italy               27
5            C       Channel Islands               24
31           C                Sweden               24
18           C                 Japan               23
1            C             Australia               22
22           C           Netherlands               21
11           C               Finland               11
8            C               Denmark               10
25           C                Poland               10
6            C                Cyprus                8
24           C                Norway                8
21           C                 Malta                7
2            C               Austria                6
15           C             Hong Kong                6
34           C  United Arab Emirates                6
33           C                   USA                5
36           C           Unspecified                4
7            C        Czech Republic                3
14           C                Greece                3
29           C             Singapore                3
3            C               Bahrain                2
10           C    European Community                1
16           C                Israel                1
19           C                 Korea                1
20           C               Lebanon                1
23           C               Nigeria                1
27           C                   RSA                1
28           C          Saudi Arabia                1

In [25]:
df.assign(
    InvoiceType=df["Invoice"].astype(str).str[0]
).query(
    "InvoiceType in ['C', 'A']"
).groupby("InvoiceType")["Country"].nunique()

InvoiceType
A     1
C    36
Name: Country, dtype: int64

In [26]:
df[df["Description"].isna()].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Amount,InvoiceType
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom,-0.0,4
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom,-0.0,4
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom,0.0,4
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom,0.0,4
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom,-0.0,4
4566,489821,85049G,NaN,-240,2009-12-02 13:25:00,0.0,NaN,United Kingdom,-0.0,4
6378,489882,35751C,NaN,12,2009-12-02 16:22:00,0.0,NaN,United Kingdom,0.0,4
6555,489898,79323G,NaN,954,2009-12-03 09:40:00,0.0,NaN,United Kingdom,0.0,4
6576,489901,21098,NaN,-200,2009-12-03 09:47:00,0.0,NaN,United Kingdom,-0.0,4
6581,489903,21166,NaN,48,2009-12-03 09:57:00,0.0,NaN,United Kingdom,0.0,4

In [27]:
df[df["Description"].isna()]["Invoice"].astype(str).str[0].value_counts()

Invoice
5    3334
4    1048
Name: count, dtype: int64

In [28]:
df[df["Customer ID"].isna()]["Invoice"].astype(str).str[0].value_counts()

Invoice
5    213302
4     28949
C       750
A         6
Name: count, dtype: int64

In [29]:
df[df["Customer ID"].isna()].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Amount,InvoiceType
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.00,NaN,United Kingdom,-0.00,4
283,489463,71477,short,-240,2009-12-01 10:52:00,0.00,NaN,United Kingdom,-0.00,4
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.00,NaN,United Kingdom,-0.00,4
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.00,NaN,United Kingdom,-0.00,4
577,489525,85226C,BLUE PULL BACK RACING CAR,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom,0.55,4
578,489525,85227,SET/6 3D KIT CARDS FOR KIDS,1,2009-12-01 11:49:00,0.85,NaN,United Kingdom,0.85,4
1055,489548,22271,FELTCRAFT DOLL ROSIE,1,2009-12-01 12:32:00,2.95,NaN,United Kingdom,2.95,4
1056,489548,22254,FELT TOADSTOOL LARGE,12,2009-12-01 12:32:00,1.25,NaN,United Kingdom,15.00,4
1057,489548,22273,FELTCRAFT DOLL MOLLY,3,2009-12-01 12:32:00,2.95,NaN,United Kingdom,8.85,4
1058,489548,22195,LARGE HEART MEASURING SPOONS,1,2009-12-01 12:32:00,1.65,NaN,United Kingdom,1.65,4

In [30]:
df[df["Customer ID"].isna()]["Country"].value_counts().head(20)

Country
United Kingdom          240029
EIRE                      1671
Hong Kong                  364
Unspecified                232
France                     128
Switzerland                125
Portugal                   116
United Arab Emirates       114
Bahrain                     67
Israel                      47
RSA                         46
Bermuda                     34
Sweden                      19
Lebanon                     13
Nigeria                      2
Name: count, dtype: int64

In [31]:
df[df["Price"] <= 0].groupby(
    df["Invoice"].astype(str).str[0]
).size()

Invoice
4    1108
5    5094
A       5
dtype: int64

In [32]:
df[df["Price"] <= 0][
    ["Invoice", "StockCode", "Description", "Quantity", "Price", "Customer ID", "Country"]
].head(20)

,Invoice,StockCode,Description,Quantity,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,0.0,NaN,United Kingdom
283,489463,71477,short,-240,0.0,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,0.0,NaN,United Kingdom
470,489521,21646,NaN,-50,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,0.0,NaN,United Kingdom
3162,489660,35956,lost,-1043,0.0,NaN,United Kingdom
3168,489663,35605A,damages,-117,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,0.0,NaN,United Kingdom
4538,489820,21133,invcd as 84879?,-720,0.0,NaN,United Kingdom
4566,489821,85049G,NaN,-240,0.0,NaN,United Kingdom
4674,489825,22076,6 RIBBONS EMPIRE,12,0.0,16126.0,United Kingdom
5904,489861,DOT,DOTCOM POSTAGE,1,0.0,NaN,United Kingdom
6378,489882,35751C,NaN,12,0.0,NaN,United Kingdom
6555,489898,79323G,NaN,954,0.0,NaN,United Kingdom
6556,489899,79323GR,sold as gold,-954,0.0,NaN,United Kingdom
6576,489901,21098,NaN,-200,0.0,NaN,United Kingdom
6581,489903,21166,NaN,48,0.0,NaN,United Kingdom
6781,489998,48185,DOOR MAT FAIRY CAKE,2,0.0,15658.0,United Kingdom

In [33]:
(df["Price"] <= 0).sum()

np.int64(6207)

In [34]:
negative_price = df[df["Price"] < 0]

negative_price.groupby(
    negative_price["Invoice"].astype(str).str[0]
).size()

Invoice
A    5
dtype: int64

In [35]:
price_by_invoice_type = (
    df.assign(
        InvoiceType=df["Invoice"].astype(str).str[0]
    )
    .groupby("InvoiceType")
    .agg(
        Total_Rows=("Price", "size"),
        Zero_Price=("Price", lambda x: (x == 0).sum()),
        Negative_Price=("Price", lambda x: (x < 0).sum()),
        Positive_Price=("Price", lambda x: (x > 0).sum())
    )
    .reset_index()
)

price_by_invoice_type

  InvoiceType  Total_Rows  Zero_Price  Negative_Price  Positive_Price
0           4      108489        1108               0          107381
1           5      939382        5094               0          934288
2           A           6           0               5               1
3           C       19494           0               0           19494

In [36]:
c_negative_price = df[
    (df["Invoice"].astype(str).str.startswith("C")) &
    (df["Price"] < 0)
]

print("Number of C invoices with negative price:", len(c_negative_price))

Number of C invoices with negative price: 0